# Build Stage
FROM microsoft/aspnetcore-build:2 as build-env

WORKDIR /API
COPY . .
RUN dotnet restore
RUN dotnet publish -o /publish

WORKDIR /publish

# Runtime Stage
FROM microsoft/aspnetcore:2 as run-env
WORKDIR /publish
COPY --from=build-env /publish /publish
ENTRYPOINT [ "dotnet","/publish/api.dll" ]